version: "3.9"

volumes: 
  data:

networks: 
  frontend:
    external: true
    name: npm-net
  backend:

services:

  nginx:
    build: 
      context: ./nginx
    env_file: .env
    volumes: 
      - ./app/static:/static/:ro
      - ./app/media:/media/:ro
    networks:
      frontend:
        aliases:
          - nginx
    expose:
      - "${NGINX_PORT}"
    environment: 
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_PORT=80
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
      - DJANGO_PORT=${DJANGO_PORT}
      - DJANGO_APP_ROOT=${DJANGO_APP_ROOT}
      - FORCE_SCRIPT_NAME=${FORCE_SCRIPT_NAME}
    restart: "on-failure"
    depends_on: 
      - app
    # logging: 
    #   driver: syslog
    #   options: 
    #     syslog-address: "tcp://127.0.0.1:514"
    #     tag: "{{.DaemonName}}/{{.Name}}"
    
  app:
    build: 
      context: .
    env_file: .env
    volumes:
      - ./app:${DJANGO_APP_ROOT}:rw
      - ./app/static:${DJANGO_APP_ROOT}/static:rw
      - ./app/media:${DJANGO_APP_ROOT}/media:rw
    networks:
      frontend:
        aliases:
          - app
      backend:
    environment: 
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      # - FORCE_SCRIPT_NAME=${FORCE_SCRIPT_NAME}
    command: >
      sh -c "/wait-for-it.sh --host='${MYSQL_HOST}' --port='${MYSQL_PORT}' --timeout=0 -- \
                  python manage.py collectstatic --no-input &&
                  python manage.py runserver 0:${DJANGO_PORT}"
    depends_on: 
      - db
    restart: "on-failure"
    # logging: 
    #   driver: syslog
    #   options: 
    #     syslog-address: "tcp://127.0.0.1:514"
    #     tag: "{{.DaemonName}}/{{.Name}}"

  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file: .env
    volumes: 
      - data:/var/lib/mysql
    networks: 
      backend:
        aliases:
          - db
    restart: "unless-stopped"
    # logging: 
    #   driver: syslog
    #   options: 
    #     syslog-address: "tcp://127.0.0.1:514"
    #     tag: "{{.DaemonName}}/{{.Name}}"
