version: "3.9"

networks: 
  frontend:

services:
  nginx:
    build: 
      context: ./nginx
    env_file: .env
    volumes: 
      - ./app/static:/static/:ro
      - ./app/media:/media/:ro
      - ./nginx/templates:/etc/nginx/templates
    networks: 
      - frontend
    restart: "on-failure"
    depends_on: 
      - app
    
  app:
    build: 
      context: .
    env_file: .env
    networks:
      - frontend
    restart: "on-failure"